# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /c/Users/NoName/Documents/Programming/OpenHL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /c/Users/NoName/Documents/Programming/OpenHL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/NoName/Documents/Programming/OpenHL/CMakeFiles /c/Users/NoName/Documents/Programming/OpenHL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/NoName/Documents/Programming/OpenHL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example_sha

# Build rule for target.
example_sha: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_sha
.PHONY : example_sha

# fast build rule for target.
example_sha/fast:
	$(MAKE) -f CMakeFiles/example_sha.dir/build.make CMakeFiles/example_sha.dir/build
.PHONY : example_sha/fast

#=============================================================================
# Target rules for targets named openhl

# Build rule for target.
openhl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openhl
.PHONY : openhl

# fast build rule for target.
openhl/fast:
	$(MAKE) -f CMakeFiles/openhl.dir/build.make CMakeFiles/openhl.dir/build
.PHONY : openhl/fast

examples/example_sha.obj: examples/example_sha.c.obj

.PHONY : examples/example_sha.obj

# target to build an object file
examples/example_sha.c.obj:
	$(MAKE) -f CMakeFiles/example_sha.dir/build.make CMakeFiles/example_sha.dir/examples/example_sha.c.obj
.PHONY : examples/example_sha.c.obj

examples/example_sha.i: examples/example_sha.c.i

.PHONY : examples/example_sha.i

# target to preprocess a source file
examples/example_sha.c.i:
	$(MAKE) -f CMakeFiles/example_sha.dir/build.make CMakeFiles/example_sha.dir/examples/example_sha.c.i
.PHONY : examples/example_sha.c.i

examples/example_sha.s: examples/example_sha.c.s

.PHONY : examples/example_sha.s

# target to generate assembly for a file
examples/example_sha.c.s:
	$(MAKE) -f CMakeFiles/example_sha.dir/build.make CMakeFiles/example_sha.dir/examples/example_sha.c.s
.PHONY : examples/example_sha.c.s

src/sha.obj: src/sha.c.obj

.PHONY : src/sha.obj

# target to build an object file
src/sha.c.obj:
	$(MAKE) -f CMakeFiles/openhl.dir/build.make CMakeFiles/openhl.dir/src/sha.c.obj
.PHONY : src/sha.c.obj

src/sha.i: src/sha.c.i

.PHONY : src/sha.i

# target to preprocess a source file
src/sha.c.i:
	$(MAKE) -f CMakeFiles/openhl.dir/build.make CMakeFiles/openhl.dir/src/sha.c.i
.PHONY : src/sha.c.i

src/sha.s: src/sha.c.s

.PHONY : src/sha.s

# target to generate assembly for a file
src/sha.c.s:
	$(MAKE) -f CMakeFiles/openhl.dir/build.make CMakeFiles/openhl.dir/src/sha.c.s
.PHONY : src/sha.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... example_sha"
	@echo "... openhl"
	@echo "... examples/example_sha.obj"
	@echo "... examples/example_sha.i"
	@echo "... examples/example_sha.s"
	@echo "... src/sha.obj"
	@echo "... src/sha.i"
	@echo "... src/sha.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

